### PR TITLE
Dockblock and code formatting

### PR DESCRIPTION
**Pull request by mos3abof**
- Added docblock comments to all classes, methods, and traits
- Code formatted all PHP files.

Resolves issue #2: https://github.com/pckg/migrator/issues/2

### CODE REVIEW

**Comment by schtr4jh** [comment]
Hi @mos3abof,

thanks for contribution! May I ask you to reformat code with 4 spaces instead of tab? If using Phpstorm simply set code standards to scheme PSR1/2 and reformat again. This way is impossible to review changes.

Regards and thanks again!

**Comment by mos3abof** [comment]
@schtr4jh, sure. I will do that later today.

**Comment by mos3abof** [comment]
@schtr4jh, converted all tabs to spaces.

**Comment by schtr4jh** [comment]
@mos3abof Thanks, I've merged your changes to master. ;)

**Pull request merged**
